/** Safe barrel */

export { KonexError } from './app.error';
export { createAuthError } from './app.error';
export { createValidationError } from './app.error';
export { createDatabaseError } from './app.error';
export { createNetworkError } from './app.error';
export { createNotFoundError } from './app.error';
export { createPermissionDeniedError } from './app.error';
export { createDuplicateError } from './app.error';
export { createSquadFullError } from './app.error';
export { createSquadInviteOnlyError } from './app.error';
export { createPostNotFoundError } from './app.error';
export { createCommentNotFoundError } from './app.error';
export { createSquadAlreadyMemberError } from './app.error';
export { default as AppError } from './app.error';
export { ErrorCode } from './error.codes';
export { ErrorSeverity } from './error.codes';
export { ErrorCategories } from './error.codes';
export { ErrorMessages } from './error.codes';
export { ErrorSeverityMap } from './error.codes';
export { default as ErrorCodes } from './error.codes';
export { errorHandler } from './error.handler';
export { handleError } from './error.handler';
export { handleRecoverableError } from './error.handler';
export { handleFatalError } from './error.handler';
export { addErrorListener } from './error.handler';
export { removeErrorListener } from './error.handler';
export { updateErrorHandler } from './error.handler';
export { getErrorStats } from './error.handler';
export { resetErrorHandler } from './error.handler';
export type { ErrorHandlerConfig } from './error.handler';
export type { ErrorContext } from './error.handler';
export type { ErrorResult } from './error.handler';
export { default as ErrorHandler } from './error.handler';
export { UserErrorMessages } from './error.messages';
export { LocalizedErrorMessages } from './error.messages';
export { getUserErrorMessage } from './error.messages';
export { getUserMessageFromError } from './error.messages';
export type { ErrorMessageLocalization } from './error.messages';
