/** Safe barrel - no duplicates */

export { AuthValidator } from './auth.validator';
export type { AuthValidatorInput } from './auth.validator';
export type { AuthValidatorOutput } from './auth.validator';
export { PostValidator } from './post.validator';
export type { PostValidatorInput } from './post.validator';
export type { CommentValidatorInput } from './post.validator';
export type { PostValidatorOutput } from './post.validator';
export type { CommentValidatorOutput } from './post.validator';
export { SquadValidator } from './squad.validator';
export type { SquadValidatorInput } from './squad.validator';
export type { SquadValidatorOutput } from './squad.validator';
export { UserValidator } from './user.validator';
export type { UserValidatorInput } from './user.validator';
export type { UserValidatorOutput } from './user.validator';
export { REGEX_PATTERNS } from './validation.utils';
export { validateEmail } from './validation.utils';
export { validatePassword } from './validation.utils';
export { validateUsername } from './validation.utils';
export { validateGamerTag } from './validation.utils';
export { validateBio } from './validation.utils';
export { validateUrl } from './validation.utils';
export { validatePhone } from './validation.utils';
export { validateLength } from './validation.utils';
export { validateRequired } from './validation.utils';
export { validateRegex } from './validation.utils';
export { validateSlug } from './validation.utils';
export { validateUUID } from './validation.utils';
export { validateHexColor } from './validation.utils';
export { validateSignUpInput } from './validation.utils';
export { validateLoginInput } from './validation.utils';
export { validateProfileUpdateInput } from './validation.utils';
export { validateSquadCreationInput } from './validation.utils';
export { validatePostCreationInput } from './validation.utils';
export type { ValidationResult } from './validation.utils';
export type { ValidationError } from './validation.utils';
export type { ValidationResultWithErrors } from './validation.utils';
export { default as ValidationUtils } from './validation.utils';
