export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          username: string;
          display_name: string;
          email: string;
          phone_number: string | null;
          profile_picture: string | null;
          cover_photo: string | null;
          bio: string | null;
          country: string;
          city: string | null;
          region: string | null;
          gender: string | null;
          birth_date: string | null;
          favorite_games: string[];
          platforms: string[];
          gaming_skills: Json;
          followers: string[];
          following: string[];
          friends: string[];
          blocked: string[];
          badges: string[];
          posts: string[];
          squads: string[];
          communities: string[];
          stats: Json;
          settings: Json;
          role: string;
          is_verified: boolean;
          is_active: boolean;
          is_suspended: boolean;
          is_banned: boolean;
          suspension_reason: string | null;
          ban_reason: string | null;
          last_active: string;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          username: string;
          display_name: string;
          email: string;
          phone_number?: string | null;
          profile_picture?: string | null;
          cover_photo?: string | null;
          bio?: string | null;
          country: string;
          city?: string | null;
          region?: string | null;
          gender?: string | null;
          birth_date?: string | null;
          favorite_games?: string[];
          platforms?: string[];
          gaming_skills?: Json;
          followers?: string[];
          following?: string[];
          friends?: string[];
          blocked?: string[];
          badges?: string[];
          posts?: string[];
          squads?: string[];
          communities?: string[];
          stats?: Json;
          settings?: Json;
          role?: string;
          is_verified?: boolean;
          is_active?: boolean;
          is_suspended?: boolean;
          is_banned?: boolean;
          suspension_reason?: string | null;
          ban_reason?: string | null;
          last_active?: string;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          username?: string;
          display_name?: string;
          email?: string;
          phone_number?: string | null;
          profile_picture?: string | null;
          cover_photo?: string | null;
          bio?: string | null;
          country?: string;
          city?: string | null;
          region?: string | null;
          gender?: string | null;
          birth_date?: string | null;
          favorite_games?: string[];
          platforms?: string[];
          gaming_skills?: Json;
          followers?: string[];
          following?: string[];
          friends?: string[];
          blocked?: string[];
          badges?: string[];
          posts?: string[];
          squads?: string[];
          communities?: string[];
          stats?: Json;
          settings?: Json;
          role?: string;
          is_verified?: boolean;
          is_active?: boolean;
          is_suspended?: boolean;
          is_banned?: boolean;
          suspension_reason?: string | null;
          ban_reason?: string | null;
          last_active?: string;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
      };
      communities: {
        Row: {
          id: string;
          name: string;
          slug: string;
          description: string | null;
          logo: string | null;
          cover_image: string | null;
          type: string;
          category: string;
          visibility: string;
          game: string | null;
          region: string | null;
          country: string | null;
          city: string | null;
          rules: Json;
          members: Json;
          posts: string[];
          squads: string[];
          tournaments: string[];
          lfg: string[];
          moderators: string[];
          stats: Json;
          tags: string[];
          is_verified: boolean;
          is_active: boolean;
          is_featured: boolean;
          created_by: string;
          settings: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          description?: string | null;
          logo?: string | null;
          cover_image?: string | null;
          type: string;
          category: string;
          visibility?: string;
          game?: string | null;
          region?: string | null;
          country?: string | null;
          city?: string | null;
          rules?: Json;
          members?: Json;
          posts?: string[];
          squads?: string[];
          tournaments?: string[];
          lfg?: string[];
          moderators?: string[];
          stats?: Json;
          tags?: string[];
          is_verified?: boolean;
          is_active?: boolean;
          is_featured?: boolean;
          created_by: string;
          settings?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          description?: string | null;
          logo?: string | null;
          cover_image?: string | null;
          type?: string;
          category?: string;
          visibility?: string;
          game?: string | null;
          region?: string | null;
          country?: string | null;
          city?: string | null;
          rules?: Json;
          members?: Json;
          posts?: string[];
          squads?: string[];
          tournaments?: string[];
          lfg?: string[];
          moderators?: string[];
          stats?: Json;
          tags?: string[];
          is_verified?: boolean;
          is_active?: boolean;
          is_featured?: boolean;
          created_by?: string;
          settings?: Json;
          created_at?: string;
          updated_at?: string;
        };
      };
      squads: {
        Row: {
          id: string;
          name: string;
          slug: string;
          logo: string | null;
          cover_image: string | null;
          description: string | null;
          type: string;
          game: string;
          game_mode: string;
          skill_level: string;
          rank: string | null;
          status: string;
          max_members: number;
          members: Json;
          pending_requests: string[];
          banned_members: string[];
          posts: string[];
          chat_id: string | null;
          tournaments: string[];
          leader: string;
          co_leaders: string[];
          moderators: string[];
          tags: string[];
          requirements: Json;
          stats: Json;
          settings: Json;
          is_verified: boolean;
          is_active: boolean;
          is_featured: boolean;
          created_by: string;
          created_at: string;
          updated_at: string;
          archived_at: string | null;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          logo?: string | null;
          cover_image?: string | null;
          description?: string | null;
          type: string;
          game: string;
          game_mode: string;
          skill_level: string;
          rank?: string | null;
          status?: string;
          max_members?: number;
          members?: Json;
          pending_requests?: string[];
          banned_members?: string[];
          posts?: string[];
          chat_id?: string | null;
          tournaments?: string[];
          leader: string;
          co_leaders?: string[];
          moderators?: string[];
          tags?: string[];
          requirements: Json;
          stats?: Json;
          settings?: Json;
          is_verified?: boolean;
          is_active?: boolean;
          is_featured?: boolean;
          created_by: string;
          created_at?: string;
          updated_at?: string;
          archived_at?: string | null;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          logo?: string | null;
          cover_image?: string | null;
          description?: string | null;
          type?: string;
          game?: string;
          game_mode?: string;
          skill_level?: string;
          rank?: string | null;
          status?: string;
          max_members?: number;
          members?: Json;
          pending_requests?: string[];
          banned_members?: string[];
          posts?: string[];
          chat_id?: string | null;
          tournaments?: string[];
          leader?: string;
          co_leaders?: string[];
          moderators?: string[];
          tags?: string[];
          requirements?: Json;
          stats?: Json;
          settings?: Json;
          is_verified?: boolean;
          is_active?: boolean;
          is_featured?: boolean;
          created_by?: string;
          created_at?: string;
          updated_at?: string;
          archived_at?: string | null;
        };
      };
      posts: {
        Row: {
          id: string;
          type: string;
          category: string;
          author: string;
          content: Json;
          visibility: string;
          status: string;
          tags: string[];
          game_tags: string[];
          mentions: string[];
          likes: string[];
          comments: string[];
          shares: number;
          saves: number;
          reports: string[];
          is_pinned: boolean;
          is_edited: boolean;
          is_featured: boolean;
          is_sponsored: boolean;
          parent_post_id: string | null;
          community_id: string | null;
          squad_id: string | null;
          tournament_id: string | null;
          lfg_id: string | null;
          scheduled_for: string | null;
          stats: Json;
          analytics: Json;
          created_at: string;
          updated_at: string;
          published_at: string | null;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          type: string;
          category: string;
          author: string;
          content: Json;
          visibility: string;
          status?: string;
          tags?: string[];
          game_tags?: string[];
          mentions?: string[];
          likes?: string[];
          comments?: string[];
          shares?: number;
          saves?: number;
          reports?: string[];
          is_pinned?: boolean;
          is_edited?: boolean;
          is_featured?: boolean;
          is_sponsored?: boolean;
          parent_post_id?: string | null;
          community_id?: string | null;
          squad_id?: string | null;
          tournament_id?: string | null;
          lfg_id?: string | null;
          scheduled_for?: string | null;
          stats?: Json;
          analytics?: Json;
          created_at?: string;
          updated_at?: string;
          published_at?: string | null;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          type?: string;
          category?: string;
          author?: string;
          content?: Json;
          visibility?: string;
          status?: string;
          tags?: string[];
          game_tags?: string[];
          mentions?: string[];
          likes?: string[];
          comments?: string[];
          shares?: number;
          saves?: number;
          reports?: string[];
          is_pinned?: boolean;
          is_edited?: boolean;
          is_featured?: boolean;
          is_sponsored?: boolean;
          parent_post_id?: string | null;
          community_id?: string | null;
          squad_id?: string | null;
          tournament_id?: string | null;
          lfg_id?: string | null;
          scheduled_for?: string | null;
          stats?: Json;
          analytics?: Json;
          created_at?: string;
          updated_at?: string;
          published_at?: string | null;
          deleted_at?: string | null;
        };
      };
      comments: {
        Row: {
          id: string;
          post_id: string;
          user_id: string;
          content: string;
          media: Json | null;
          mentions: string[];
          likes: string[];
          replies: string[];
          parent_comment_id: string | null;
          is_edited: boolean;
          is_pinned: boolean;
          is_deleted: boolean;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          post_id: string;
          user_id: string;
          content: string;
          media?: Json | null;
          mentions?: string[];
          likes?: string[];
          replies?: string[];
          parent_comment_id?: string | null;
          is_edited?: boolean;
          is_pinned?: boolean;
          is_deleted?: boolean;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          post_id?: string;
          user_id?: string;
          content?: string;
          media?: Json | null;
          mentions?: string[];
          likes?: string[];
          replies?: string[];
          parent_comment_id?: string | null;
          is_edited?: boolean;
          is_pinned?: boolean;
          is_deleted?: boolean;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
      };
      chats: {
        Row: {
          id: string;
          type: string;
          name: string | null;
          avatar: string | null;
          participants: string[];
          last_message: Json | null;
          last_message_at: string | null;
          unread_count: Json;
          status: string;
          is_pinned: boolean;
          settings: Json;
          squad_id: string | null;
          community_id: string | null;
          created_by: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          type: string;
          name?: string | null;
          avatar?: string | null;
          participants: string[];
          last_message?: Json | null;
          last_message_at?: string | null;
          unread_count?: Json;
          status?: string;
          is_pinned?: boolean;
          settings?: Json;
          squad_id?: string | null;
          community_id?: string | null;
          created_by: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          type?: string;
          name?: string | null;
          avatar?: string | null;
          participants?: string[];
          last_message?: Json | null;
          last_message_at?: string | null;
          unread_count?: Json;
          status?: string;
          is_pinned?: boolean;
          settings?: Json;
          squad_id?: string | null;
          community_id?: string | null;
          created_by?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      messages: {
        Row: {
          id: string;
          chat_id: string;
          sender_id: string;
          type: string;
          content: Json;
          status: string;
          is_deleted: boolean;
          is_edited: boolean;
          reactions: Json;
          reply_to: string | null;
          forwarded_from: string | null;
          read_by: string[];
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          chat_id: string;
          sender_id: string;
          type: string;
          content: Json;
          status?: string;
          is_deleted?: boolean;
          is_edited?: boolean;
          reactions?: Json;
          reply_to?: string | null;
          forwarded_from?: string | null;
          read_by?: string[];
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          chat_id?: string;
          sender_id?: string;
          type?: string;
          content?: Json;
          status?: string;
          is_deleted?: boolean;
          is_edited?: boolean;
          reactions?: Json;
          reply_to?: string | null;
          forwarded_from?: string | null;
          read_by?: string[];
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
      };
      lfg: {
        Row: {
          id: string;
          game_id: string;
          game_mode: string;
          map: string | null;
          mode: string;
          skill_level: string;
          players_needed: number;
          players_joined: number;
          current_players: string[];
          creator_id: string;
          platform: string[];
          language: string[];
          region: string;
          country: string;
          description: string | null;
          requirements: Json;
          mic_required: boolean;
          voice_chat_platform: string | null;
          start_time: string | null;
          expiration_time: string;
          status: string;
          squad_id: string | null;
          community_id: string | null;
          tags: string[];
          applications: Json;
          stats: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          game_id: string;
          game_mode: string;
          map?: string | null;
          mode: string;
          skill_level: string;
          players_needed: number;
          players_joined?: number;
          current_players?: string[];
          creator_id: string;
          platform: string[];
          language: string[];
          region: string;
          country: string;
          description?: string | null;
          requirements: Json;
          mic_required: boolean;
          voice_chat_platform?: string | null;
          start_time?: string | null;
          expiration_time: string;
          status?: string;
          squad_id?: string | null;
          community_id?: string | null;
          tags?: string[];
          applications?: Json;
          stats?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          game_id?: string;
          game_mode?: string;
          map?: string | null;
          mode?: string;
          skill_level?: string;
          players_needed?: number;
          players_joined?: number;
          current_players?: string[];
          creator_id?: string;
          platform?: string[];
          language?: string[];
          region?: string;
          country?: string;
          description?: string | null;
          requirements?: Json;
          mic_required?: boolean;
          voice_chat_platform?: string | null;
          start_time?: string | null;
          expiration_time?: string;
          status?: string;
          squad_id?: string | null;
          community_id?: string | null;
          tags?: string[];
          applications?: Json;
          stats?: Json;
          created_at?: string;
          updated_at?: string;
        };
      };
      tournaments: {
        Row: {
          id: string;
          name: string;
          description: string | null;
          game: string;
          game_mode: string;
          type: string;
          format: string;
          status: string;
          max_players: number;
          max_teams: number;
          registered_players: number;
          registered_teams: number;
          minimum_rank: string | null;
          minimum_level: number | null;
          entry_fee: Json | null;
          prize: Json;
          rules: Json;
          schedule: Json;
          brackets: Json;
          teams: Json;
          players: string[];
          community_id: string | null;
          squad_id: string | null;
          created_by: string;
          moderators: string[];
          stats: Json;
          is_public: boolean;
          is_verified: boolean;
          tags: string[];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          description?: string | null;
          game: string;
          game_mode: string;
          type: string;
          format: string;
          status?: string;
          max_players?: number;
          max_teams?: number;
          registered_players?: number;
          registered_teams?: number;
          minimum_rank?: string | null;
          minimum_level?: number | null;
          entry_fee?: Json | null;
          prize: Json;
          rules: Json;
          schedule: Json;
          brackets?: Json;
          teams?: Json;
          players?: string[];
          community_id?: string | null;
          squad_id?: string | null;
          created_by: string;
          moderators?: string[];
          stats?: Json;
          is_public?: boolean;
          is_verified?: boolean;
          tags?: string[];
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          description?: string | null;
          game?: string;
          game_mode?: string;
          type?: string;
          format?: string;
          status?: string;
          max_players?: number;
          max_teams?: number;
          registered_players?: number;
          registered_teams?: number;
          minimum_rank?: string | null;
          minimum_level?: number | null;
          entry_fee?: Json | null;
          prize?: Json;
          rules?: Json;
          schedule?: Json;
          brackets?: Json;
          teams?: Json;
          players?: string[];
          community_id?: string | null;
          squad_id?: string | null;
          created_by?: string;
          moderators?: string[];
          stats?: Json;
          is_public?: boolean;
          is_verified?: boolean;
          tags?: string[];
          created_at?: string;
          updated_at?: string;
        };
      };
      notifications: {
        Row: {
          id: string;
          user_id: string;
          type: string;
          title: string;
          body: string;
          data: Json;
          priority: string;
          status: string;
          action: Json | null;
          created_at: string;
          read_at: string | null;
          dismissed_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          type: string;
          title: string;
          body: string;
          data: Json;
          priority?: string;
          status?: string;
          action?: Json | null;
          created_at?: string;
          read_at?: string | null;
          dismissed_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          type?: string;
          title?: string;
          body?: string;
          data?: Json;
          priority?: string;
          status?: string;
          action?: Json | null;
          created_at?: string;
          read_at?: string | null;
          dismissed_at?: string | null;
        };
      };
      reports: {
        Row: {
          id: string;
          type: string;
          target_id: string;
          reporter_id: string;
          reason: string;
          description: string | null;
          evidence: Json | null;
          status: string;
          created_at: string;
          updated_at: string;
          resolved_at: string | null;
          resolved_by: string | null;
          action_taken: string | null;
        };
        Insert: {
          id?: string;
          type: string;
          target_id: string;
          reporter_id: string;
          reason: string;
          description?: string | null;
          evidence?: Json | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
          resolved_at?: string | null;
          resolved_by?: string | null;
          action_taken?: string | null;
        };
        Update: {
          id?: string;
          type?: string;
          target_id?: string;
          reporter_id?: string;
          reason?: string;
          description?: string | null;
          evidence?: Json | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
          resolved_at?: string | null;
          resolved_by?: string | null;
          action_taken?: string | null;
        };
      };
      moderation_queue: {
        Row: {
          id: string;
          content_id: string;
          content_type: string;
          reported_by: string;
          reason: string;
          description: string | null;
          evidence: Json | null;
          status: string;
          priority: string;
          assigned_to: string | null;
          action: string | null;
          action_details: string | null;
          created_at: string;
          updated_at: string;
          resolved_at: string | null;
          resolved_by: string | null;
        };
        Insert: {
          id?: string;
          content_id: string;
          content_type: string;
          reported_by: string;
          reason: string;
          description?: string | null;
          evidence?: Json | null;
          status?: string;
          priority?: string;
          assigned_to?: string | null;
          action?: string | null;
          action_details?: string | null;
          created_at?: string;
          updated_at?: string;
          resolved_at?: string | null;
          resolved_by?: string | null;
        };
        Update: {
          id?: string;
          content_id?: string;
          content_type?: string;
          reported_by?: string;
          reason?: string;
          description?: string | null;
          evidence?: Json | null;
          status?: string;
          priority?: string;
          assigned_to?: string | null;
          action?: string | null;
          action_details?: string | null;
          created_at?: string;
          updated_at?: string;
          resolved_at?: string | null;
          resolved_by?: string | null;
        };
      };
      badges: {
        Row: {
          id: string;
          name: string;
          description: string;
          icon: string;
          type: string;
          rarity: string;
          game: string | null;
          requirements: Json;
          xp_reward: number;
          is_hidden: boolean;
          is_limited: boolean;
          expires_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          description: string;
          icon: string;
          type: string;
          rarity: string;
          game?: string | null;
          requirements: Json;
          xp_reward: number;
          is_hidden?: boolean;
          is_limited?: boolean;
          expires_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          description?: string;
          icon?: string;
          type?: string;
          rarity?: string;
          game?: string | null;
          requirements?: Json;
          xp_reward?: number;
          is_hidden?: boolean;
          is_limited?: boolean;
          expires_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      user_badges: {
        Row: {
          id: string;
          user_id: string;
          badge_id: string;
          earned_at: string;
          progress: Json;
          is_displayed: boolean;
        };
        Insert: {
          id?: string;
          user_id: string;
          badge_id: string;
          earned_at?: string;
          progress?: Json;
          is_displayed?: boolean;
        };
        Update: {
          id?: string;
          user_id?: string;
          badge_id?: string;
          earned_at?: string;
          progress?: Json;
          is_displayed?: boolean;
        };
      };
      stories: {
        Row: {
          id: string;
          user_id: string;
          media: Json;
          text: string | null;
          seen_by: string[];
          expires_at: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          media: Json;
          text?: string | null;
          seen_by?: string[];
          expires_at: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          media?: Json;
          text?: string | null;
          seen_by?: string[];
          expires_at?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      games: {
        Row: {
          id: string;
          name: string;
          slug: string;
          logo: string | null;
          cover_image: string | null;
          genre: string[];
          platforms: string[];
          description: string | null;
          developer: string;
          publisher: string | null;
          release_date: string | null;
          rating: number | null;
          total_players: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          logo?: string | null;
          cover_image?: string | null;
          genre: string[];
          platforms: string[];
          description?: string | null;
          developer: string;
          publisher?: string | null;
          release_date?: string | null;
          rating?: number | null;
          total_players?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          logo?: string | null;
          cover_image?: string | null;
          genre?: string[];
          platforms?: string[];
          description?: string | null;
          developer?: string;
          publisher?: string | null;
          release_date?: string | null;
          rating?: number | null;
          total_players?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      follows: {
        Row: {
          id: string;
          follower_id: string;
          following_id: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          follower_id: string;
          following_id: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          follower_id?: string;
          following_id?: string;
          created_at?: string;
        };
      };
      friend_requests: {
        Row: {
          id: string;
          sender_id: string;
          receiver_id: string;
          status: string;
          message: string | null;
          created_at: string;
          updated_at: string;
          responded_at: string | null;
        };
        Insert: {
          id?: string;
          sender_id: string;
          receiver_id: string;
          status?: string;
          message?: string | null;
          created_at?: string;
          updated_at?: string;
          responded_at?: string | null;
        };
        Update: {
          id?: string;
          sender_id?: string;
          receiver_id?: string;
          status?: string;
          message?: string | null;
          created_at?: string;
          updated_at?: string;
          responded_at?: string | null;
        };
      };
      blocks: {
        Row: {
          id: string;
          blocker_id: string;
          blocked_id: string;
          reason: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          blocker_id: string;
          blocked_id: string;
          reason?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          blocker_id?: string;
          blocked_id?: string;
          reason?: string | null;
          created_at?: string;
        };
      };
      analytics: {
        Row: {
          id: string;
          event_type: string;
          user_id: string | null;
          session_id: string | null;
          data: Json;
          ip: string | null;
          user_agent: string | null;
          platform: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          event_type: string;
          user_id?: string | null;
          session_id?: string | null;
          data: Json;
          ip?: string | null;
          user_agent?: string | null;
          platform?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          event_type?: string;
          user_id?: string | null;
          session_id?: string | null;
          data?: Json;
          ip?: string | null;
          user_agent?: string | null;
          platform?: string | null;
          created_at?: string;
        };
      };
    };
    Views: {
      user_stats: {
        Row: {
          user_id: string;
          posts_count: number;
          followers_count: number;
          following_count: number;
          friends_count: number;
          squads_count: number;
          tournaments_played: number;
          tournaments_won: number;
          lfg_created: number;
          lfg_joined: number;
          badges_count: number;
          total_likes_received: number;
          total_comments_received: number;
          xp: number;
          level: number;
        };
      };
      community_stats: {
        Row: {
          community_id: string;
          members_count: number;
          posts_count: number;
          squads_count: number;
          tournaments_count: number;
          lfg_count: number;
          total_likes: number;
          total_comments: number;
          active_members: number;
          daily_active: number;
        };
      };
      squad_stats: {
        Row: {
          squad_id: string;
          members_count: number;
          matches_played: number;
          matches_won: number;
          win_rate: number;
          tournaments_won: number;
          total_xp: number;
        };
      };
      tournament_stats: {
        Row: {
          tournament_id: string;
          total_matches: number;
          completed_matches: number;
          participant_count: number;
          view_count: number;
        };
      };
      post_stats: {
        Row: {
          post_id: string;
          likes_count: number;
          comments_count: number;
          shares_count: number;
          saves_count: number;
          views_count: number;
          engagement_rate: number;
        };
      };
    };
    Functions: {
      get_user_feed: {
        Args: { user_id: string; limit?: number; offset?: number };
        Returns: Json;
      };
      search_users: {
        Args: { query: string; limit?: number; offset?: number };
        Returns: Json;
      };
      search_posts: {
        Args: { query: string; limit?: number; offset?: number };
        Returns: Json;
      };
      get_nearby_users: {
        Args: { user_id: string; radius?: number };
        Returns: Json;
      };
      calculate_user_xp: {
        Args: { user_id: string };
        Returns: number;
      };
      get_tournament_bracket: {
        Args: { tournament_id: string };
        Returns: Json;
      };
      update_tournament_bracket: {
        Args: { tournament_id: string; match_id: string; winner_id: string };
        Returns: void;
      };
      check_user_badges: {
        Args: { user_id: string };
        Returns: Json;
      };
    };
    Enums: {
      user_role: 'user' | 'moderator' | 'admin' | 'super_admin';
      user_status: 'online' | 'offline' | 'idle' | 'do_not_disturb';
      community_type: 'gaming' | 'regional' | 'squad' | 'tournament' | 'general' | 'official';
      squad_status: 'active' | 'inactive' | 'full' | 'recruiting' | 'locked' | 'archived';
      post_type: 'text' | 'image' | 'video' | 'link' | 'poll' | 'tournament' | 'lfg' | 'story' | 'event';
      notification_type: 'friend_request' | 'friend_accepted' | 'follow' | 'like' | 'comment' | 'mention' | 'message' | 'squad_invite' | 'lfg_request' | 'tournament_update' | 'badge_earned' | 'level_up';
      report_reason: 'spam' | 'harassment' | 'hate_speech' | 'violence' | 'nudity' | 'cheating' | 'scam' | 'impersonation' | 'inappropriate';
      moderation_action: 'dismiss' | 'warning' | 'temporary_suspension' | 'permanent_suspension' | 'ban' | 'content_removal' | 'content_hidden';
      badge_rarity: 'common' | 'uncommon' | 'rare' | 'epic' | 'legendary' | 'mythic';
      lfg_status: 'open' | 'in_progress' | 'full' | 'cancelled' | 'expired';
      tournament_format: 'single_elimination' | 'double_elimination' | 'round_robin' | 'group_stage';
      tournament_status: 'draft' | 'upcoming' | 'open' | 'in_progress' | 'completed' | 'cancelled';
      squad_role: 'leader' | 'co_leader' | 'moderator' | 'member' | 'trial';
    };
  };
}