/**
 * api.video client flow:
 * 1) Authenticated call to Supabase Edge Function (server holds API key)
 * 2) Upload bytes to api.video upload URL with short-lived access token
 * 3) Poll status edge function until ready (thumbnail + mp4)
 *
 * The long-lived API.video API key is NEVER embedded in this client module.
 */
import * as FileSystem from 'expo-file-system';
import { supabase } from '../client/supabase.client';
import {
  MEDIA_MAX_BYTES,
  MEDIA_MAX_VIDEO_DURATION_SEC,
  MEDIA_TOO_LARGE_MESSAGE,
} from './media.constants';
import { validateLocalMedia } from './mediaValidate';

export type VideoUploadProgress = {
  phase: 'validating' | 'uploading' | 'processing' | 'completed' | 'failed' | 'cancelled';
  percent?: number;
  message?: string;
};

export type ApiVideoResult = {
  video_id: string;
  mp4_url: string | null;
  hls_url: string | null;
  thumbnail_url: string | null;
  player_url: string | null;
  status: string;
  file_size: number;
};

async function sleep(ms: number) {
  return new Promise((r) => setTimeout(r, ms));
}

export async function uploadVideoToApiVideo(params: {
  uri: string;
  mime?: string;
  title?: string;
  durationSec?: number;
  cancelRef?: { cancelled: boolean };
  onProgress?: (p: VideoUploadProgress) => void;
}): Promise<ApiVideoResult> {
  const { uri, mime, title, durationSec, cancelRef, onProgress } = params;

  onProgress?.({ phase: 'validating', message: 'Validating video…' });
  if (durationSec != null && durationSec > MEDIA_MAX_VIDEO_DURATION_SEC) {
    throw new Error(`Video is too long. Maximum duration is ${MEDIA_MAX_VIDEO_DURATION_SEC} seconds.`);
  }

  const { size } = await validateLocalMedia({
    uri,
    mime: mime || 'video/mp4',
    kind: 'video',
  });

  if (cancelRef?.cancelled) throw cancelledError();

  onProgress?.({ phase: 'uploading', percent: 5, message: 'Creating video slot…' });

  const { data: created, error: createErr } = await supabase.functions.invoke('api-video-create', {
    body: {
      title: title || `konex_${Date.now()}`,
      file_size: size,
      duration_sec: durationSec ?? null,
    },
  });

  if (createErr) {
    throw new Error(createErr.message || 'Failed to create api.video upload session');
  }
  if (!created?.ok) {
    throw new Error(created?.message || 'api.video create rejected');
  }

  const { video_id, upload_url, access_token } = created;
  if (!video_id || !upload_url || !access_token) {
    throw new Error('Invalid response from api-video-create');
  }

  if (cancelRef?.cancelled) throw cancelledError();
  onProgress?.({ phase: 'uploading', percent: 15, message: 'Uploading to api.video…' });

  // Upload source file to api.video
  const uploadResult = await FileSystem.uploadAsync(upload_url, uri, {
    httpMethod: 'POST',
    uploadType: FileSystem.FileSystemUploadType.MULTIPART,
    fieldName: 'file',
    mimeType: mime || 'video/mp4',
    headers: {
      Authorization: `Bearer ${access_token}`,
    },
  });

  if (cancelRef?.cancelled) throw cancelledError();

  if (uploadResult.status < 200 || uploadResult.status >= 300) {
    // Try binary POST as fallback
    const bin = await FileSystem.uploadAsync(upload_url, uri, {
      httpMethod: 'POST',
      uploadType: FileSystem.FileSystemUploadType.BINARY_CONTENT,
      headers: {
        Authorization: `Bearer ${access_token}`,
        'Content-Type': mime || 'video/mp4',
      },
    });
    if (bin.status < 200 || bin.status >= 300) {
      throw new Error(
        `api.video upload failed (${bin.status}): ${String(bin.body || '').slice(0, 200)}`
      );
    }
  }

  onProgress?.({ phase: 'processing', percent: 70, message: 'Processing video & thumbnail…' });

  // Poll until ready (thumbnail auto-generated by api.video)
  let last: any = null;
  for (let i = 0; i < 40; i++) {
    if (cancelRef?.cancelled) throw cancelledError();
    const { data: st, error: stErr } = await supabase.functions.invoke('api-video-status', {
      body: { video_id },
    });
    if (stErr) {
      throw new Error(stErr.message || 'Status check failed');
    }
    last = st;
    if (st?.status === 'ready' && (st.mp4_url || st.hls_url || st.thumbnail_url)) {
      onProgress?.({ phase: 'completed', percent: 100, message: 'Ready' });
      return {
        video_id,
        mp4_url: st.mp4_url,
        hls_url: st.hls_url,
        thumbnail_url: st.thumbnail_url,
        player_url: st.player_url,
        status: 'ready',
        file_size: size,
      };
    }
    onProgress?.({
      phase: 'processing',
      percent: Math.min(95, 70 + i),
      message: 'Processing video & thumbnail…',
    });
    await sleep(2000);
  }

  // Still processing — return what we have; post should wait or show processing
  if (last?.ok) {
    return {
      video_id,
      mp4_url: last.mp4_url,
      hls_url: last.hls_url,
      thumbnail_url: last.thumbnail_url,
      player_url: last.player_url,
      status: last.status || 'processing',
      file_size: size,
    };
  }

  throw new Error('Video processing timed out. Try again later.');
}

function cancelledError() {
  const e = new Error('Upload cancelled');
  (e as any).code = 'UPLOAD_CANCELLED';
  return e;
}
